
.SUFFIXES:
.SUFFIXES: .ml .mli .mll .cmo .cmi .cma .js .byte

.ml.cmo:
	$(CAMLC) -c $(FLAGS) $<

.mli.cmi:
	$(CAMLC) -c $(FLAGS) $<

.mll.ml:
	$(CAMLLEX) $<

.mll.cmo:
	$(CAMLLEX) $<
	$(CAMLC) -c $(FLAGS) $*.ml