
FLAGS = -bin-annot -g -annot
JSPKGS = -package js_of_ocaml,js_of_ocaml.syntax,js_of_ocaml_compiler,js_of_ocaml_compiler-libs \
	 -syntax camlp4o -linkpkg

REPKG= -package re

CAMLC = ocamlc
CAMLLEX = ocamllex
CAMLDEP = ocamldep
CAMLFIND = ocamlfind
CAMLJS = $(CAMLFIND) $(CAMLC) $(JSPKGS) $(FLAGS) 

OPAMLIB= ~/.opam/4.00.1/lib

PP = "camlp4o ~/.opam/4.00.1/lib/js_of_ocaml/pa_js.cmo"
